# frozen_string_literal: true

source 'https://rubygems.org'

gem 'facter', ENV['FACTER_GEM_VERSION'], require: false
gem 'puppet', ENV['PUPPET_GEM_VERSION'], require: false

group :development, :test do
  gem 'metadata-json-lint',             require: false
  gem 'puppet-lint', '~> 2.3.5',        require: false
  gem 'puppet-syntax',                  require: false
  gem 'puppetlabs_spec_helper', '~> 2', require: false
  gem 'rake',                           require: false
end
