# frozen_string_literal: true

source 'https://rubygems.org'

gem 'puppet', '~> 5.5.6'
gem 'rake'

group :development, :test do
  gem 'metadata-json-lint',             require: false
  gem 'puppet-lint', '~> 2.3.5',        require: false
  gem 'puppet-syntax',                  require: false
  gem 'puppetlabs_spec_helper', '~> 2', require: false
end
