#!/usr/bin/env ruby
# frozen_string_literal: true

# Parse a yaml file and then [re]dump the de-serialization as yaml. This may be
# useful for checking formatting and/or processing of anchor/aliases.

require 'yaml'

foo = YAML.load_file(ARGV[0])
puts YAML.dump(foo)
