#aws_zone_id = ""
#dns_enable = "true"
#domain_name = ""
#env_name = ""
#group_name = ""
grafana_oauth_team_ids = "1936535"
#jenkins_agent_executors = "1"
#jenkins_agent_pass = ""
#jenkins_agent_replicas = ""
#jenkins_agent_user = ""
#jenkins_agent_volume_size = "250Gi"
#master_fqdn = ""
prometheus_github_org = "lsst-sqre"
#tls_crt_path = ""
#tls_key_path = ""

